config/routes.rb
Re::Application.routes.draw do
  resource :settings, only: [:show, :update]

  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'

  post '/tracker' => 'trackers#create'
  get '/tracker/:id/tracker.jpg' => 'trackers#show', as: 'tracker_snippet'

  root 'homepage#index'

  PagesController.action_methods.each do |action|
     get "/#{action}", to: "pages##{action}", as: "#{action}_page"
  end

end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
  has_many :views
  belongs_to :user

  validates_presence_of :message_token, :sender, :recipient
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :api_key, presence: true
  mount_uploader :signature_image, SignatureImageUploader

  before_validation :generate_api_key!, on: :create

  def generate_api_key!
    self.api_key = SecureRandom.uuid
  end
end

app/models/view.rb
class View < ActiveRecord::Base
  belongs_to :tracker
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def require_authentication
    unless authenticated?
      flash[:error] = "Bitte melde dich erst an"
      redirect_to root_url
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def ueber
  end

  def hilfe
  end

  def faq
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    respond_to_browserid
    if browserid_email.present? && current_user.blank?
      create_new_persona_user
    end
  end

  def destroy
    logout_browserid
    head :ok
  end

  private

  def create_new_persona_user
    User.create!(email: browserid_email) # Fails loudly!
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :require_authentication

  def show
  end

  def update
    current_user.update_attributes(user_params)
    flash[:notice] = "Einstellungen wurden gespeichert"
    redirect_to settings_path
  end

  private

  def user_params
    params.require(:user).permit(
      :signature_image_setting,
      :signature_image,
      :remove_signature_image
      )
  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :require_api_authentication, only: :create
  helper_method :client_ip

  def create
    @tracker = Tracker.create!(message_token: SecureRandom.uuid,
      user: current_api_user,
      recipient: params[:recipient],
      subject: params[:subject],
      sender: current_api_user.email)
    render layout: false
  end

  def show
    tracker = Tracker.where(message_token: params[:id]).first!
    unless params[:notrack]
      view = View.create!(tracker: tracker, request_ip: client_ip, user_agent: request.user_agent)
      ReceiptMailer.read_confirmation(tracker, view).deliver
    end
    # FIXME Spec this
    if tracker.user.signature_image_setting == 'gravatar'
      data = Gravatar.new(tracker.user.email).image_data(size: 50)
      send_data data, type: 'image/jpeg', disposition: 'inline'
      return
    end
    image_path = if tracker.user.signature_image_setting == 'custom'
      tracker.user.signature_image.versions[:mini].path
    else
      Rails.root.join('app/assets/images/fallback/tracker.png')
    end
    send_file(image_path, disposition: 'inline')
  end

  private

  def require_api_authentication
    if current_api_user.blank?
      render text: 'not allowed', status: 401
    end
  end

  def current_api_user
    User.where(api_key: params[:api_key]).first
  end

  def client_ip
    header_ip = request.env['HTTP_X_FORWARDED_FOR'].try(:split, ',').try(:first)
    header_ip || request.remote_ip
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  module_function

  def gravatar_url_for(email, options = { size: 50 })
    Gravatar.new(email).image_url(options)
  end

end

app/views/homepage/index.html.slim
.page-header
  h1
    ' Re:
    br
    small E-Mail Empfangsbestätigung für Jedermann

.jumbotron
  .container

    h3 Und so geht's:

    ol
      li Tracker-Plugin installieren
      li E-Mail versenden
      li Empfangsbestätigung bekommen sobald die E-Mail geöffnet wird

    - if authenticated?
      .btn-group
        <button type="button" class="btn btn-primary dropdown-toggle btn-lg" data-toggle="dropdown">
          | Tracker-Plugin herunterladen
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><a href="https://github.com/sbange/re-thunderbird/releases/download/initial/re-thunderbird.xpi">Plugin für Thunderbird</a></li>
        </ul>


      h5 Dein API-Key:
      form
        fieldset
          .input-group.col-lg-2
            = text_field_tag("current-user-api-key", current_user.api_key, readonly: true, class: 'form-control input-sm input-login-token')
            span.input-group-btn
              button.btn.btn-sm(data-clipboard-target="current-user-api-key")
                i.icon-copy

    - else
      = link_to login_path, class: 'browserid_login btn btn-primary btn-lg'
        | Mit E-Mail anmelden


.row
  .col-md-8.col-md-offset-2
    h3 Projektidee
    .text
      markdown:
        Behörden und große Unternehmen wie z.B. Google speichern und analysieren alle Anfragen an ihre Server, um mehr über ihre Kunden zu erfahren. Das Projekt Re will solche Methoden aufzeigen und transparent machen, indem es dem Kunden bzw. Bürger die gleichen Werkzeuge bereitstellt. Mit _Re_ kann jedermann das Verhalten von Unternehmen und Behörden analysieren.

        Beim BremenHack wurde ein Server entwickelt, der jedem eine Datensammlung und eine Auswertung erlaubt. Als erstes Beispiel für eine konkrete Datensammlung stellt Re ein Add-On für das E-Mail-Programm Thunderbird zur Verfügung. Es sammelt Daten über den Empfänger einer E-Mail und meldet z.B. jedes Öffnen der Email an den Versender: eine "Empfangsbestätigung für jedermann".

  div(style="text-align: center;")
    = image_tag 'briefe.png'

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      = link_to 'Re:', root_url,  class: 'navbar-brand'
      p.navbar-text.navbar-right
        - if authenticated?
          '  eingeloggt als
          = link_to browserid_email, settings_path
    ul.nav.navbar-nav.navbar-right
      - if authenticated?
        li  = link_to "Einstellungen", settings_path
        li  = logout_link "Abmelden"
      - else
        li = login_link

app/views/layouts/application.html.slim
doctype 5
html.no-js lang=(I18n.locale || 'de')
  head
    title Re: Email-Empfangsbestätigung für alle!
    meta name='apple-mobile-web-app-capable' content='yes'
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = setup_browserid debug: false
    /[if lte IE 8]
      javascript:
        'article aside footer header nav section time'.replace(/\w+/g,function(n){document.createElement(n)})

  body
    - if authenticated?
      = render 'layouts/navbar'
    .container
      = yield

    hr
    footer.footer
      .container
        p
          ' Ein
          = link_to 'BremenHack', 'http://bremen.stadthack.de'
          '-Projekt von
          = link_to 'Andreas Haller', 'http://ahax.de'
          ',
          =' link_to 'Eckhard Rotte', 'http://erotte.de'
          ' und
          =' link_to 'Sven Bange', 'http://spurtreu.de'
          |– 
          = link_to 'Quellcode auf GitHub', 'http://github.com/ahx/re'

app/views/pages/hilfe.html.slim
h1 Hilfe

app/views/pages/ueber.html.slim
h1 Über das Projekt

app/views/settings/show.html.slim
= form_for current_user, url: settings_path, :html => {multipart: true, role: 'form', class: 'form-vertical'} do |f|
  h4 Ändere Dein Tracker-Bild
  p Du kannst selbst bestimmen, ob dein Tracker-Code unsichbar sein soll oder ob eine Grafik eingefügt werden soll.
  .form-group
    .radio
      label
        = f.radio_button(:signature_image_setting, "gravatar")
        = image_tag(gravatar_url_for(current_user.email), alt: nil)
        ' Gravatar
  .form-group
    .radio
      label
        = f.radio_button(:signature_image_setting, "custom")
        = image_tag(current_user.signature_image.url(:mini), alt: nil)
        ' Eigenes Bild
      = f.file_field :signature_image
  .form-group
    .radio
      label
        = f.radio_button(:signature_image_setting, "none")
        ' Kein Bild
  p
    = f.submit 'Einstellung Speichern', class: 'btn btn-primary'
    = link_to 'Abbrechen', root_path, class: 'btn btn-link'

app/views/trackers/create.html.erb
<img src="<%= tracker_snippet_url(id: @tracker.message_token) %>" moz-do-not-send="true">